services:
  - type: worker
    name: garolab-sniper-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        fromSecret: TELEGRAM_BOT_TOKEN
      - key: TELEGRAM_CHAT_ID
        fromSecret: TELEGRAM_CHAT_ID
      - key: PRIVATE_KEY
        fromSecret: PRIVATE_KEY
      - key: RPC_URL
        fromSecret: RPC_URL
      - key: MORALIS_API_KEY
        fromSecret: MORALIS_API_KEY
      - key: AUTO_BUY
        value: "1"
      - key: TRADE_SIZE_SOL
        value: "1"
      - key: SLIPPAGE_BPS
        value: "50"
      - key: TAKE_PROFIT_MULTIPLE
        value: "2.0"
      - key: POLL_INTERVAL
        value: "5"
